//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Test1.rc
//
#define IDS_STRING1                     1
#define IDI_APPL                        101
#define IDI_LOGO                        102
#define IDD_DIALOG1                     103
#define IDC_CHECK1                      1005
#define IDC_SPIN1                       1006
#define IDC_EDIT1                       1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
